# Sample configuration
# Logging level for the application. One of debug, info, warn, or error
log-level: "info"
# Storage configuration
storage:
  # Storage type. One of mysql, postgres, sqlite
  type: "sqlite"
  # Data source name for the storage
  dsn: "file:./.dinner-elo.db?cache=shared&mode=rwc"
# HTTP server configuration
http:
  # URL where the HTTP server is deployed, used for redirects. Required
  # url: ""
  # IP address to listen on. Empty listens on all interfaces
  # address: ""
  # Port to listen on
  port: 8080
  # Trusted proxies for the HTTP server
  # trusted-proxies: []
# Metrics server configuration
metrics:
  # Enable metrics server
  enabled: false
  # Address to listen on
  # address: ""
  # Port to listen on
  port: 9000
# PProf server configuration
pprof:
  # Enable pprof server
  enabled: false
  # Address to listen on
  # address: ""
  # Port to listen on
  port: 9999
# Authentication configuration
auth:
  # JWT secret for signing tokens. Required
  # jwt-secret: "(secret)"
  # OAuth2 client ID
  # client-id: ""
  # OAuth2 client secret
  # client-secret: "(secret)"
  # OAuth2 token URL, e.g. https://example.com/oauth2/token
  # token-url: ""
  # OAuth2 user information URL, e.g. https://example.com/oauth2/userinfo
  # user-url: ""
