// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type storageShadow struct {
	Type *string `json:"type" toml:"type" yaml:"type"`
	DSN  *string `json:"dsn"  toml:"dsn"  yaml:"dsn"`
}

type hTTPShadow struct {
	URL            *string   `json:"url"             toml:"url"             yaml:"url"`
	Address        *string   `json:"address"         toml:"address"         yaml:"address"`
	Port           *int      `json:"port"            toml:"port"            yaml:"port"`
	TrustedProxies *[]string `json:"trusted-proxies" toml:"trusted-proxies" yaml:"trusted-proxies"`
}

type metricsShadow struct {
	Enabled *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	Address *string `json:"address" toml:"address" yaml:"address"`
	Port    *int    `json:"port"    toml:"port"    yaml:"port"`
}

type pProfShadow struct {
	Enabled *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	Address *string `json:"address" toml:"address" yaml:"address"`
	Port    *int    `json:"port"    toml:"port"    yaml:"port"`
}

type authShadow struct {
	JWTSecret    *string `json:"jwt-secret"    toml:"jwt-secret"    yaml:"jwt-secret"`
	ClientID     *string `json:"client-id"     toml:"client-id"     yaml:"client-id"`
	ClientSecret *string `json:"client-secret" toml:"client-secret" yaml:"client-secret"`
	TokenURL     *string `json:"token-url"     toml:"token-url"     yaml:"token-url"`
	UserURL      *string `json:"user-url"      toml:"user-url"      yaml:"user-url"`
}

type configShadow struct {
	LogLevel *string        `json:"log-level" toml:"log-level" yaml:"log-level"`
	Storage  *storageShadow `json:"storage"   toml:"storage"   yaml:"storage"`
	HTTP     *hTTPShadow    `json:"http"      toml:"http"      yaml:"http"`
	Metrics  *metricsShadow `json:"metrics"   toml:"metrics"   yaml:"metrics"`
	PProf    *pProfShadow   `json:"pprof"     toml:"pprof"     yaml:"pprof"`
	Auth     *authShadow    `json:"auth"      toml:"auth"      yaml:"auth"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.Storage.Type = StorageType("sqlite")
	set("storage.type", configulator.LayerDefault, "default tag")
	cfg.Storage.DSN = "file:./.dinner-elo.db?cache=shared&mode=rwc"
	set("storage.dsn", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = 8080
	set("http.port", configulator.LayerDefault, "default tag")
	cfg.Metrics.Port = 9000
	set("metrics.port", configulator.LayerDefault, "default tag")
	cfg.PProf.Port = 9999
	set("pprof.port", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.Storage != nil {
		if s.Storage.Type != nil {
			cfg.Storage.Type = StorageType(*s.Storage.Type)
			set("storage.type", configulator.LayerFile, file)
		}
		if s.Storage.DSN != nil {
			cfg.Storage.DSN = *s.Storage.DSN
			set("storage.dsn", configulator.LayerFile, file)
		}
	}
	if s.HTTP != nil {
		if s.HTTP.URL != nil {
			cfg.HTTP.URL = *s.HTTP.URL
			set("http.url", configulator.LayerFile, file)
		}
		if s.HTTP.Address != nil {
			cfg.HTTP.Address = *s.HTTP.Address
			set("http.address", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
		if s.HTTP.TrustedProxies != nil {
			cfg.HTTP.TrustedProxies = *s.HTTP.TrustedProxies
			set("http.trusted-proxies", configulator.LayerFile, file)
		}
	}
	if s.Metrics != nil {
		if s.Metrics.Enabled != nil {
			cfg.Metrics.Enabled = *s.Metrics.Enabled
			set("metrics.enabled", configulator.LayerFile, file)
		}
		if s.Metrics.Address != nil {
			cfg.Metrics.Address = *s.Metrics.Address
			set("metrics.address", configulator.LayerFile, file)
		}
		if s.Metrics.Port != nil {
			cfg.Metrics.Port = *s.Metrics.Port
			set("metrics.port", configulator.LayerFile, file)
		}
	}
	if s.PProf != nil {
		if s.PProf.Enabled != nil {
			cfg.PProf.Enabled = *s.PProf.Enabled
			set("pprof.enabled", configulator.LayerFile, file)
		}
		if s.PProf.Address != nil {
			cfg.PProf.Address = *s.PProf.Address
			set("pprof.address", configulator.LayerFile, file)
		}
		if s.PProf.Port != nil {
			cfg.PProf.Port = *s.PProf.Port
			set("pprof.port", configulator.LayerFile, file)
		}
	}
	if s.Auth != nil {
		if s.Auth.JWTSecret != nil {
			cfg.Auth.JWTSecret = *s.Auth.JWTSecret
			set("auth.jwt-secret", configulator.LayerFile, file)
		}
		if s.Auth.ClientID != nil {
			cfg.Auth.ClientID = *s.Auth.ClientID
			set("auth.client-id", configulator.LayerFile, file)
		}
		if s.Auth.ClientSecret != nil {
			cfg.Auth.ClientSecret = *s.Auth.ClientSecret
			set("auth.client-secret", configulator.LayerFile, file)
		}
		if s.Auth.TokenURL != nil {
			cfg.Auth.TokenURL = *s.Auth.TokenURL
			set("auth.token-url", configulator.LayerFile, file)
		}
		if s.Auth.UserURL != nil {
			cfg.Auth.UserURL = *s.Auth.UserURL
			set("auth.user-url", configulator.LayerFile, file)
		}
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "log-level"); ok {
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "storage", "type"); ok {
		cfg.Storage.Type = StorageType(v)
		set("storage.type", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "storage", "dsn"); ok {
		cfg.Storage.DSN = v
		set("storage.dsn", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "url"); ok {
		cfg.HTTP.URL = v
		set("http.url", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "address"); ok {
		cfg.HTTP.Address = v
		set("http.address", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Port = int(p)
		set("http.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "trusted-proxies"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.HTTP.TrustedProxies = lst
		set("http.trusted-proxies", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.Metrics.Enabled = p
		set("metrics.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "address"); ok {
		cfg.Metrics.Address = v
		set("metrics.address", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "metrics", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Metrics.Port = int(p)
		set("metrics.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "pprof", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.PProf.Enabled = p
		set("pprof.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "pprof", "address"); ok {
		cfg.PProf.Address = v
		set("pprof.address", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "pprof", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.PProf.Port = int(p)
		set("pprof.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "jwt-secret"); ok {
		cfg.Auth.JWTSecret = v
		set("auth.jwt-secret", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "client-id"); ok {
		cfg.Auth.ClientID = v
		set("auth.client-id", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "client-secret"); ok {
		cfg.Auth.ClientSecret = v
		set("auth.client-secret", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "token-url"); ok {
		cfg.Auth.TokenURL = v
		set("auth.token-url", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "auth", "user-url"); ok {
		cfg.Auth.UserURL = v
		set("auth.user-url", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"log-level",
		"storage" + o.Separator + "type",
		"storage" + o.Separator + "dsn",
		"http" + o.Separator + "url",
		"http" + o.Separator + "address",
		"http" + o.Separator + "port",
		"http" + o.Separator + "trusted-proxies",
		"metrics" + o.Separator + "enabled",
		"metrics" + o.Separator + "address",
		"metrics" + o.Separator + "port",
		"pprof" + o.Separator + "enabled",
		"pprof" + o.Separator + "address",
		"pprof" + o.Separator + "port",
		"auth" + o.Separator + "jwt-secret",
		"auth" + o.Separator + "client-id",
		"auth" + o.Separator + "client-secret",
		"auth" + o.Separator + "token-url",
		"auth" + o.Separator + "user-url",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.String(names[1], "sqlite", "Storage type. One of mysql, postgres, sqlite")
	fs.String(names[2], "file:./.dinner-elo.db?cache=shared&mode=rwc", "Data source name for the storage")
	fs.String(names[3], "", "URL where the HTTP server is deployed, used for redirects. Required")
	fs.String(names[4], "", "IP address to listen on. Empty listens on all interfaces")
	fs.Var(impl.NewInt(8080), names[5], "Port to listen on")
	fs.StringSlice(names[6], nil, "Trusted proxies for the HTTP server")
	fs.Bool(names[7], false, "Enable metrics server")
	fs.String(names[8], "", "Address to listen on")
	fs.Var(impl.NewInt(9000), names[9], "Port to listen on")
	fs.Bool(names[10], false, "Enable pprof server")
	fs.String(names[11], "", "Address to listen on")
	fs.Var(impl.NewInt(9999), names[12], "Port to listen on")
	fs.String(names[13], "", "JWT secret for signing tokens. Required")
	fs.String(names[14], "", "OAuth2 client ID")
	fs.String(names[15], "", "OAuth2 client secret")
	fs.String(names[16], "", "OAuth2 token URL, e.g. https://example.com/oauth2/token")
	fs.String(names[17], "", "OAuth2 user information URL, e.g. https://example.com/oauth2/userinfo")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "log-level"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := "storage" + o.Separator + "type"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "storage.type",
				Source: "--" + n,
			}
		}
		cfg.Storage.Type = StorageType(v)
		set("storage.type", configulator.LayerCLI, "--"+n)
	}
	if n := "storage" + o.Separator + "dsn"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "storage.dsn",
				Source: "--" + n,
			}
		}
		cfg.Storage.DSN = v
		set("storage.dsn", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.url",
				Source: "--" + n,
			}
		}
		cfg.HTTP.URL = v
		set("http.url", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "address"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.address",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Address = v
		set("http.address", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "trusted-proxies"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.trusted-proxies",
				Source: "--" + n,
			}
		}
		cfg.HTTP.TrustedProxies = v
		set("http.trusted-proxies", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Enabled = v
		set("metrics.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "address"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.address",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Address = v
		set("metrics.address", configulator.LayerCLI, "--"+n)
	}
	if n := "metrics" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.port",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Port = v
		set("metrics.port", configulator.LayerCLI, "--"+n)
	}
	if n := "pprof" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.enabled",
				Source: "--" + n,
			}
		}
		cfg.PProf.Enabled = v
		set("pprof.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "pprof" + o.Separator + "address"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.address",
				Source: "--" + n,
			}
		}
		cfg.PProf.Address = v
		set("pprof.address", configulator.LayerCLI, "--"+n)
	}
	if n := "pprof" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.port",
				Source: "--" + n,
			}
		}
		cfg.PProf.Port = v
		set("pprof.port", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "jwt-secret"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.jwt-secret",
				Source: "--" + n,
			}
		}
		cfg.Auth.JWTSecret = v
		set("auth.jwt-secret", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "client-id"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.client-id",
				Source: "--" + n,
			}
		}
		cfg.Auth.ClientID = v
		set("auth.client-id", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "client-secret"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.client-secret",
				Source: "--" + n,
			}
		}
		cfg.Auth.ClientSecret = v
		set("auth.client-secret", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "token-url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.token-url",
				Source: "--" + n,
			}
		}
		cfg.Auth.TokenURL = v
		set("auth.token-url", configulator.LayerCLI, "--"+n)
	}
	if n := "auth" + o.Separator + "user-url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.user-url",
				Source: "--" + n,
			}
		}
		cfg.Auth.UserURL = v
		set("auth.user-url", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return configJSONError("log-level", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "storage":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("storage", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub storageShadow
				if err := sub.decodeJSON(dec, "storage"); err != nil {
					return err
				}
				s.Storage = &sub
			}
		case "http":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("http", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub hTTPShadow
				if err := sub.decodeJSON(dec, "http"); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "metrics":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("metrics", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub metricsShadow
				if err := sub.decodeJSON(dec, "metrics"); err != nil {
					return err
				}
				s.Metrics = &sub
			}
		case "pprof":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("pprof", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub pProfShadow
				if err := sub.decodeJSON(dec, "pprof"); err != nil {
					return err
				}
				s.PProf = &sub
			}
		case "auth":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("auth", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub authShadow
				if err := sub.decodeJSON(dec, "auth"); err != nil {
					return err
				}
				s.Auth = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *storageShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "type":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Type = &str
			default:
				return configJSONError(path+".type", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "dsn":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.DSN = &str
			default:
				return configJSONError(path+".dsn", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *hTTPShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.URL = &str
			default:
				return configJSONError(path+".url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "address":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Address = &str
			default:
				return configJSONError(path+".address", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "trusted-proxies":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".trusted-proxies", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".trusted-proxies"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TrustedProxies = &out
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *metricsShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "address":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Address = &str
			default:
				return configJSONError(path+".address", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *pProfShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "address":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Address = &str
			default:
				return configJSONError(path+".address", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *authShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "jwt-secret":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.JWTSecret = &str
				default:
					return configJSONError(path+".jwt-secret", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".jwt-secret",
					Value: "(redacted)",
				}
			}
		case "client-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.ClientID = &str
			default:
				return configJSONError(path+".client-id", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "client-secret":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.ClientSecret = &str
				default:
					return configJSONError(path+".client-secret", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".client-secret",
					Value: "(redacted)",
				}
			}
		case "token-url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.TokenURL = &str
			default:
				return configJSONError(path+".token-url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "user-url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.UserURL = &str
			default:
				return configJSONError(path+".user-url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "log-level = %v\n", c.LogLevel)
	fmt.Fprintf(&b, "storage.type = %v\n", c.Storage.Type)
	fmt.Fprintf(&b, "storage.dsn = %v\n", c.Storage.DSN)
	fmt.Fprintf(&b, "http.url = %v\n", c.HTTP.URL)
	fmt.Fprintf(&b, "http.address = %v\n", c.HTTP.Address)
	fmt.Fprintf(&b, "http.port = %v\n", c.HTTP.Port)
	fmt.Fprintf(&b, "http.trusted-proxies = %v\n", c.HTTP.TrustedProxies)
	fmt.Fprintf(&b, "metrics.enabled = %v\n", c.Metrics.Enabled)
	fmt.Fprintf(&b, "metrics.address = %v\n", c.Metrics.Address)
	fmt.Fprintf(&b, "metrics.port = %v\n", c.Metrics.Port)
	fmt.Fprintf(&b, "pprof.enabled = %v\n", c.PProf.Enabled)
	fmt.Fprintf(&b, "pprof.address = %v\n", c.PProf.Address)
	fmt.Fprintf(&b, "pprof.port = %v\n", c.PProf.Port)
	b.WriteString("auth.jwt-secret = (redacted)\n")
	fmt.Fprintf(&b, "auth.client-id = %v\n", c.Auth.ClientID)
	b.WriteString("auth.client-secret = (redacted)\n")
	fmt.Fprintf(&b, "auth.token-url = %v\n", c.Auth.TokenURL)
	fmt.Fprintf(&b, "auth.user-url = %v\n", c.Auth.UserURL)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
