// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"strconv"
	"strings"
)

type storageShadow struct {
	Type *string `json:"type" toml:"type" yaml:"type"`
	DSN  *string `json:"dsn" toml:"dsn" yaml:"dsn"`
}
type hTTPShadow struct {
	URL            *string   `json:"url" toml:"url" yaml:"url"`
	Address        *string   `json:"address" toml:"address" yaml:"address"`
	Port           *int      `json:"port" toml:"port" yaml:"port"`
	TrustedProxies *[]string `json:"trusted-proxies" toml:"trusted-proxies" yaml:"trusted-proxies"`
}
type metricsShadow struct {
	Enabled *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	Address *string `json:"address" toml:"address" yaml:"address"`
	Port    *int    `json:"port" toml:"port" yaml:"port"`
}
type pProfShadow struct {
	Enabled *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	Address *string `json:"address" toml:"address" yaml:"address"`
	Port    *int    `json:"port" toml:"port" yaml:"port"`
}
type authShadow struct {
	JWTSecret    *string `json:"jwt-secret" toml:"jwt-secret" yaml:"jwt-secret"`
	ClientID     *string `json:"client-id" toml:"client-id" yaml:"client-id"`
	ClientSecret *string `json:"client-secret" toml:"client-secret" yaml:"client-secret"`
	TokenURL     *string `json:"token-url" toml:"token-url" yaml:"token-url"`
	UserURL      *string `json:"user-url" toml:"user-url" yaml:"user-url"`
}
type configShadow struct {
	LogLevel *string        `json:"log-level" toml:"log-level" yaml:"log-level"`
	Storage  *storageShadow `json:"storage" toml:"storage" yaml:"storage"`
	HTTP     *hTTPShadow    `json:"http" toml:"http" yaml:"http"`
	Metrics  *metricsShadow `json:"metrics" toml:"metrics" yaml:"metrics"`
	PProf    *pProfShadow   `json:"pprof" toml:"pprof" yaml:"pprof"`
	Auth     *authShadow    `json:"auth" toml:"auth" yaml:"auth"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}
func configApplyDefaults(cfg *Config, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.Storage.Type = StorageType("sqlite")
	set("storage.type", configulator.LayerDefault, "default tag")
	cfg.Storage.DSN = "file:./.dinner-elo.db?cache=shared&mode=rwc"
	set("storage.dsn", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = 8080
	set("http.port", configulator.LayerDefault, "default tag")
	cfg.Metrics.Port = 9000
	set("metrics.port", configulator.LayerDefault, "default tag")
	cfg.PProf.Port = 9999
	set("pprof.port", configulator.LayerDefault, "default tag")
	return nil
}
func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *configShadow) applyTo(cfg *Config, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.Storage != nil {
		if s.Storage.Type != nil {
			cfg.Storage.Type = StorageType(*s.Storage.Type)
			set("storage.type", configulator.LayerFile, file)
		}
		if s.Storage.DSN != nil {
			cfg.Storage.DSN = *s.Storage.DSN
			set("storage.dsn", configulator.LayerFile, file)
		}
	}
	if s.HTTP != nil {
		if s.HTTP.URL != nil {
			cfg.HTTP.URL = *s.HTTP.URL
			set("http.url", configulator.LayerFile, file)
		}
		if s.HTTP.Address != nil {
			cfg.HTTP.Address = *s.HTTP.Address
			set("http.address", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
		if s.HTTP.TrustedProxies != nil {
			cfg.HTTP.TrustedProxies = *s.HTTP.TrustedProxies
			set("http.trusted-proxies", configulator.LayerFile, file)
		}
	}
	if s.Metrics != nil {
		if s.Metrics.Enabled != nil {
			cfg.Metrics.Enabled = *s.Metrics.Enabled
			set("metrics.enabled", configulator.LayerFile, file)
		}
		if s.Metrics.Address != nil {
			cfg.Metrics.Address = *s.Metrics.Address
			set("metrics.address", configulator.LayerFile, file)
		}
		if s.Metrics.Port != nil {
			cfg.Metrics.Port = *s.Metrics.Port
			set("metrics.port", configulator.LayerFile, file)
		}
	}
	if s.PProf != nil {
		if s.PProf.Enabled != nil {
			cfg.PProf.Enabled = *s.PProf.Enabled
			set("pprof.enabled", configulator.LayerFile, file)
		}
		if s.PProf.Address != nil {
			cfg.PProf.Address = *s.PProf.Address
			set("pprof.address", configulator.LayerFile, file)
		}
		if s.PProf.Port != nil {
			cfg.PProf.Port = *s.PProf.Port
			set("pprof.port", configulator.LayerFile, file)
		}
	}
	if s.Auth != nil {
		if s.Auth.JWTSecret != nil {
			cfg.Auth.JWTSecret = *s.Auth.JWTSecret
			set("auth.jwt-secret", configulator.LayerFile, file)
		}
		if s.Auth.ClientID != nil {
			cfg.Auth.ClientID = *s.Auth.ClientID
			set("auth.client-id", configulator.LayerFile, file)
		}
		if s.Auth.ClientSecret != nil {
			cfg.Auth.ClientSecret = *s.Auth.ClientSecret
			set("auth.client-secret", configulator.LayerFile, file)
		}
		if s.Auth.TokenURL != nil {
			cfg.Auth.TokenURL = *s.Auth.TokenURL
			set("auth.token-url", configulator.LayerFile, file)
		}
		if s.Auth.UserURL != nil {
			cfg.Auth.UserURL = *s.Auth.UserURL
			set("auth.user-url", configulator.LayerFile, file)
		}
	}
	return nil
}
func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "log-level"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.LogLevel = LogLevel(v)
			set("log-level", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "storage", "type"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Storage.Type = StorageType(v)
			set("storage.type", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "storage", "dsn"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Storage.DSN = v
			set("storage.dsn", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "url"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HTTP.URL = v
			set("http.url", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "address"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HTTP.Address = v
			set("http.address", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "http.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.HTTP.Port = int(p)
			set("http.port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "http", "trusted-proxies"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.HTTP.TrustedProxies = configulator.SplitList(v, ec.ArraySeparator)
			set("http.trusted-proxies", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "metrics", "enabled"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "metrics.enabled",
					Source: n,
					Value:  v,
				}
			}
			cfg.Metrics.Enabled = p
			set("metrics.enabled", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "metrics", "address"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Metrics.Address = v
			set("metrics.address", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "metrics", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "metrics.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.Metrics.Port = int(p)
			set("metrics.port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "pprof", "enabled"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "pprof.enabled",
					Source: n,
					Value:  v,
				}
			}
			cfg.PProf.Enabled = p
			set("pprof.enabled", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "pprof", "address"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.PProf.Address = v
			set("pprof.address", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "pprof", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "pprof.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.PProf.Port = int(p)
			set("pprof.port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "auth", "jwt-secret"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Auth.JWTSecret = v
			set("auth.jwt-secret", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "auth", "client-id"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Auth.ClientID = v
			set("auth.client-id", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "auth", "client-secret"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Auth.ClientSecret = v
			set("auth.client-secret", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "auth", "token-url"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Auth.TokenURL = v
			set("auth.token-url", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "auth", "user-url"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Auth.UserURL = v
			set("auth.user-url", configulator.LayerEnv, n)
		}
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}
func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"log-level"}, o.Separator), strings.Join([]string{"storage", "type"}, o.Separator), strings.Join([]string{"storage", "dsn"}, o.Separator), strings.Join([]string{"http", "url"}, o.Separator), strings.Join([]string{"http", "address"}, o.Separator), strings.Join([]string{"http", "port"}, o.Separator), strings.Join([]string{"http", "trusted-proxies"}, o.Separator), strings.Join([]string{"metrics", "enabled"}, o.Separator), strings.Join([]string{"metrics", "address"}, o.Separator), strings.Join([]string{"metrics", "port"}, o.Separator), strings.Join([]string{"pprof", "enabled"}, o.Separator), strings.Join([]string{"pprof", "address"}, o.Separator), strings.Join([]string{"pprof", "port"}, o.Separator), strings.Join([]string{"auth", "jwt-secret"}, o.Separator), strings.Join([]string{"auth", "client-id"}, o.Separator), strings.Join([]string{"auth", "client-secret"}, o.Separator), strings.Join([]string{"auth", "token-url"}, o.Separator), strings.Join([]string{"auth", "user-url"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.String(strings.Join([]string{"log-level"}, o.Separator), "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.String(strings.Join([]string{"storage", "type"}, o.Separator), "sqlite", "Storage type. One of mysql, postgres, sqlite")
	fs.String(strings.Join([]string{"storage", "dsn"}, o.Separator), "file:./.dinner-elo.db?cache=shared&mode=rwc", "Data source name for the storage")
	fs.String(strings.Join([]string{"http", "url"}, o.Separator), "", "URL where the HTTP server is deployed, used for redirects")
	fs.String(strings.Join([]string{"http", "address"}, o.Separator), "", "Address to listen on")
	fs.Int(strings.Join([]string{"http", "port"}, o.Separator), 8080, "Port to listen on")
	fs.StringSlice(strings.Join([]string{"http", "trusted-proxies"}, o.Separator), nil, "Trusted proxies for the HTTP server")
	fs.Bool(strings.Join([]string{"metrics", "enabled"}, o.Separator), false, "Enable metrics server")
	fs.String(strings.Join([]string{"metrics", "address"}, o.Separator), "", "Address to listen on")
	fs.Int(strings.Join([]string{"metrics", "port"}, o.Separator), 9000, "Port to listen on")
	fs.Bool(strings.Join([]string{"pprof", "enabled"}, o.Separator), false, "Enable pprof server")
	fs.String(strings.Join([]string{"pprof", "address"}, o.Separator), "", "Address to listen on")
	fs.Int(strings.Join([]string{"pprof", "port"}, o.Separator), 9999, "Port to listen on")
	fs.String(strings.Join([]string{"auth", "jwt-secret"}, o.Separator), "", "JWT secret for signing tokens")
	fs.String(strings.Join([]string{"auth", "client-id"}, o.Separator), "", "Client ID for authentication")
	fs.String(strings.Join([]string{"auth", "client-secret"}, o.Separator), "", "Client secret for authentication")
	fs.String(strings.Join([]string{"auth", "token-url"}, o.Separator), "", "Token URL for authentication")
	fs.String(strings.Join([]string{"auth", "user-url"}, o.Separator), "", "User URL for authentication")
	return nil
}
func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"log-level"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"storage", "type"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "storage.type",
				Source: "--" + n,
			}
		}
		cfg.Storage.Type = StorageType(v)
		set("storage.type", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"storage", "dsn"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "storage.dsn",
				Source: "--" + n,
			}
		}
		cfg.Storage.DSN = v
		set("storage.dsn", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "url"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.url",
				Source: "--" + n,
			}
		}
		cfg.HTTP.URL = v
		set("http.url", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "address"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.address",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Address = v
		set("http.address", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"http", "trusted-proxies"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.trusted-proxies",
				Source: "--" + n,
			}
		}
		cfg.HTTP.TrustedProxies = v
		set("http.trusted-proxies", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"metrics", "enabled"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Enabled = v
		set("metrics.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"metrics", "address"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.address",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Address = v
		set("metrics.address", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"metrics", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.port",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Port = v
		set("metrics.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"pprof", "enabled"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.enabled",
				Source: "--" + n,
			}
		}
		cfg.PProf.Enabled = v
		set("pprof.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"pprof", "address"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.address",
				Source: "--" + n,
			}
		}
		cfg.PProf.Address = v
		set("pprof.address", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"pprof", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "pprof.port",
				Source: "--" + n,
			}
		}
		cfg.PProf.Port = v
		set("pprof.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"auth", "jwt-secret"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.jwt-secret",
				Source: "--" + n,
			}
		}
		cfg.Auth.JWTSecret = v
		set("auth.jwt-secret", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"auth", "client-id"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.client-id",
				Source: "--" + n,
			}
		}
		cfg.Auth.ClientID = v
		set("auth.client-id", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"auth", "client-secret"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.client-secret",
				Source: "--" + n,
			}
		}
		cfg.Auth.ClientSecret = v
		set("auth.client-secret", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"auth", "token-url"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.token-url",
				Source: "--" + n,
			}
		}
		cfg.Auth.TokenURL = v
		set("auth.token-url", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"auth", "user-url"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "auth.user-url",
				Source: "--" + n,
			}
		}
		cfg.Auth.UserURL = v
		set("auth.user-url", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.LogLevel = &str
			default:
				return fmt.Errorf("log-level: expected a string, got %v", v.Kind())
			}
		case "storage":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub storageShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Storage = &sub
			}
		case "http":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub hTTPShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "metrics":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub metricsShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Metrics = &sub
			}
		case "pprof":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub pProfShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.PProf = &sub
			}
		case "auth":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub authShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Auth = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*configShadow)(nil)

func (s *storageShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "type":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Type = &str
			default:
				return fmt.Errorf("type: expected a string, got %v", v.Kind())
			}
		case "dsn":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.DSN = &str
			default:
				return fmt.Errorf("dsn: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*storageShadow)(nil)

func (s *hTTPShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.URL = &str
			default:
				return fmt.Errorf("url: expected a string, got %v", v.Kind())
			}
		case "address":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Address = &str
			default:
				return fmt.Errorf("address: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		case "trusted-proxies":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("trusted-proxies: expected an array, got %v", tok.Kind())
				}
				out := []string{}
				for dec.PeekKind() != ']' {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != '"' {
						return fmt.Errorf("trusted-proxies: expected a string element, got %v", v.Kind())
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TrustedProxies = &out
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*hTTPShadow)(nil)

func (s *metricsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Enabled = &b
			default:
				return fmt.Errorf("enabled: expected a bool, got %v", v.Kind())
			}
		case "address":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Address = &str
			default:
				return fmt.Errorf("address: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*metricsShadow)(nil)

func (s *pProfShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Enabled = &b
			default:
				return fmt.Errorf("enabled: expected a bool, got %v", v.Kind())
			}
		case "address":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Address = &str
			default:
				return fmt.Errorf("address: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*pProfShadow)(nil)

func (s *authShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "jwt-secret":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.JWTSecret = &str
			default:
				return fmt.Errorf("jwt-secret: expected a string, got %v", v.Kind())
			}
		case "client-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.ClientID = &str
			default:
				return fmt.Errorf("client-id: expected a string, got %v", v.Kind())
			}
		case "client-secret":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.ClientSecret = &str
			default:
				return fmt.Errorf("client-secret: expected a string, got %v", v.Kind())
			}
		case "token-url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.TokenURL = &str
			default:
				return fmt.Errorf("token-url: expected a string, got %v", v.Kind())
			}
		case "user-url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.UserURL = &str
			default:
				return fmt.Errorf("user-url: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*authShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("log-level = %v\n", c.LogLevel))
	b.WriteString(fmt.Sprintf("storage.type = %v\n", c.Storage.Type))
	b.WriteString(fmt.Sprintf("storage.dsn = %v\n", c.Storage.DSN))
	b.WriteString(fmt.Sprintf("http.url = %v\n", c.HTTP.URL))
	b.WriteString(fmt.Sprintf("http.address = %v\n", c.HTTP.Address))
	b.WriteString(fmt.Sprintf("http.port = %v\n", c.HTTP.Port))
	b.WriteString(fmt.Sprintf("http.trusted-proxies = %v\n", c.HTTP.TrustedProxies))
	b.WriteString(fmt.Sprintf("metrics.enabled = %v\n", c.Metrics.Enabled))
	b.WriteString(fmt.Sprintf("metrics.address = %v\n", c.Metrics.Address))
	b.WriteString(fmt.Sprintf("metrics.port = %v\n", c.Metrics.Port))
	b.WriteString(fmt.Sprintf("pprof.enabled = %v\n", c.PProf.Enabled))
	b.WriteString(fmt.Sprintf("pprof.address = %v\n", c.PProf.Address))
	b.WriteString(fmt.Sprintf("pprof.port = %v\n", c.PProf.Port))
	b.WriteString(fmt.Sprintf("auth.jwt-secret = %v\n", c.Auth.JWTSecret))
	b.WriteString(fmt.Sprintf("auth.client-id = %v\n", c.Auth.ClientID))
	b.WriteString(fmt.Sprintf("auth.client-secret = %v\n", c.Auth.ClientSecret))
	b.WriteString(fmt.Sprintf("auth.token-url = %v\n", c.Auth.TokenURL))
	b.WriteString(fmt.Sprintf("auth.user-url = %v\n", c.Auth.UserURL))
	return b.String()
}
