name: Tests

on:
  pull_request:
  push:

permissions:
  contents: read
  checks: write

jobs:
  benchmark-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: go generate ./...

      - run: CGO_ENABLED=0 go test -run ^$ -benchmem -bench=. ./...

  race-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: go generate ./...

      - name: Race tests
        run: go test ./... -race

  unit-tests:
    uses: ./.github/workflows/unit-test.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  unit-tests-coverage:
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/unit-test.yaml
    with:
      coverage: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  coverage:
    needs: unit-tests-coverage
    if: ${{ !cancelled() }}
    permissions:
      contents: read
      pull-requests: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/coverage.yaml@v2
    with:
      artifact: coverage
      file: coverage.out
      app-id: ${{ vars.AUTO_COMMIT_APP_ID }}
    secrets:
      app-key: ${{ secrets.AUTO_COMMIT_APP_KEY }}
